### ISSUE TITLE
请问可以在vue2中使用么？？

### ISSUE THREAD

**Issue by git-ysz** [hellowuxin/vue3-mindmap#10]
你的仓库内有个可以在vue2中使用[https://github.com/hellowuxin/mindmap](url)，但是当前这个vue3的版本功能更完善一些，所以问一下可否能够在vue2中引入使用（已经试过，但是什么都不显示，不清楚是不是我使用方法有问题）

**Comment by git-ysz** [comment]
另外：通过vue-cli新创建的vue3.0项目中引入。右键弹出菜单定位会出现问题，总是定位到上一次编辑后的位置，而且菜单显示内容(viewMenu, nodeMenu)不匹配

**Comment by hellowuxin** [comment]
> 你的仓库内有个可以在vue2中使用[https://github.com/hellowuxin/mindmap](url)，但是当前这个vue3的版本功能更完善一些，所以问一下可否能够在vue2中引入使用（已经试过，但是什么都不显示，不清楚是不是我使用方法有问题）

vue2自然是不能兼容vue3的，这是vue框架的问题
