### ISSUE TITLE
移动端编辑节点时，导图发生偏移

### ISSUE THREAD

**Issue by fanxing518** [hellowuxin/vue3-mindmap#16]
**Describe the bug**
移动端双击编辑节点时，当弹出软键盘时，导图会瞬间发生偏移，导致找不到编辑的节点。

**To Reproduce**
重现方法
1. 移动端打开
2. 随意缩放一下导图
3. 双击任意节点进入编辑模式
4. 弹出软键盘的同时，导图瞬间偏移，有时候偏移较多，直接飞出视野
5. 似乎只有将被编辑的节点置于窗口左上角才会减少偏移，离左上角越远，编辑的时候偏移的就越多。

**Expected behavior**
不偏移，或者被编辑的节点居中

**Smartphone (please complete the following information):**
 - Device: mate40pro
 - OS: harmony
 - Browser weixin,uc

**Comment by hellowuxin** [comment]
我用iphone XR打开我的live demo测试没发现不恰当的偏移，手头没有更多的设备进行测试，抱歉
程序运行逻辑：目前进入编辑状态时，会默认移动编辑节点到可视区域内，可能是这一块有问题
