### ISSUE TITLE
能否支持点击收缩展开子节点功能

### ISSUE THREAD

**Issue by HoroXu** [hellowuxin/vue3-mindmap#18]
请问，能否实现 
父节点 有+按钮 点击可以展开子节点， 然后再点击折叠。

**Comment by hellowuxin** [comment]
目前的解决方案是
- 折叠后的节点可以通过点击...展开
- 右键菜单折叠/展开节点

**Comment by Xiaohantx** [comment]
希望能支持有+-图标，展开收缩的话不太方便。
