### ISSUE TITLE
数据没有渲染上

### ISSUE THREAD

**Issue by annxsun** [hellowuxin/vue3-mindmap#24]
代码如下：

<img width="544" alt="截屏2021-11-30 下午5 26 39" src="https://user-images.githubusercontent.com/26404051/144020773-f5f5be66-b9c7-4d43-a89a-d1880ba13e7d.png">

效果：
<img width="1185" alt="截屏2021-11-30 下午4 49 45" src="https://user-images.githubusercontent.com/26404051/144015825-32e0cb20-62a3-4af7-ab3d-17111d23ffd7.png">

**Comment by hellowuxin** [comment]
v-model有问题吧

**Comment by annxsun** [comment]
> v-model有问题吧

能否具体一点呢？ 我是参照你的demo 写的。

**Comment by hellowuxin** [comment]
v-model="map"，你定义的data哪里有map了

**Comment by annxsun** [comment]
> v-model="map"，你定义的data哪里有map了

这个我已经改了 图片忘记更新但是还是不行

**Comment by hellowuxin** [comment]
我觉得你需要自己调试

**Comment by annxsun** [comment]
> 我觉得你需要自己调试

好吧，谢了

**Comment by yoyoping** [comment]
请问这个问题解决了吗，我也遇到了

**Comment by annxsun** [comment]
已收到你的邮件谢谢~~
