### ISSUE TITLE
页面一片空白，没有数据

### ISSUE THREAD

**Issue by yoyoping** [hellowuxin/vue3-mindmap#26]
我把文档上的代码复制下来，页面一片空白，自由一个灰色的背景
![image](https://user-images.githubusercontent.com/24878437/144803935-145aa87d-b483-486f-bc14-7c47e1210912.png)

**Comment by DanmoSAMA** [comment]
我也是这个问题

**Comment by hellowuxin** [comment]
有没有报错信息

**Comment by hellowuxin** [comment]
由于没有回复，关闭该issue
