### ISSUE TITLE
在vue-admin-template项目中使用会报错

### ISSUE THREAD

**Issue by 547176052** [hellowuxin/vue3-mindmap#30]
![image](https://user-images.githubusercontent.com/26636842/152693012-d0080457-8d07-4a76-a63f-37b7c27e284c.png)
![image](https://user-images.githubusercontent.com/26636842/152693029-b58a87aa-47ea-4304-9813-d77feae6bc68.png)

**Comment by hellowuxin** [comment]
试试 import mindmap from 'vue3-mindmap'

**Comment by 547176052** [comment]
![image](https://user-images.githubusercontent.com/26636842/152725877-7c9630ea-46e1-417a-b433-dc6deaec0214.png)
还是不行

**Comment by hellowuxin** [comment]
能不能提供一个可以复现的demo，

**Comment by 547176052** [comment]
> 能不能提供一个可以复现的demo，

链接：https://pan.baidu.com/s/175RVneKVpnO_AV4Fuv5jFA 
提取码：1234


你看下这个

**Comment by hellowuxin** [comment]
其实可以放到github上，你这个压缩包连node_modules也打包了吧？

**Comment by hellowuxin** [comment]
> > 能不能提供一个可以复现的demo，
> 
> 链接：https://pan.baidu.com/s/175RVneKVpnO_AV4Fuv5jFA 提取码：1234
> 
> 你看下这个

其实可以放到github上，你这个压缩包连node_modules也打包了吧？

**Comment by 547176052** [comment]
是的直接整个项目打包 你下载下来应该能直接运行

**Comment by hellowuxin** [comment]
哎，你这是vue2的项目啊，我这要求vue3
<img width="271" alt="截屏2022-02-22 下午8 19 51" src="https://user-images.githubusercontent.com/37543498/155131129-0efc0fa9-a7f2-499a-8a99-fc6c20a7fa0d.png">

**Comment by 547176052** [comment]
好的  非常感谢你  麻烦你了
