### ISSUE TITLE
Direction of nodes on base element

### ISSUE THREAD

**Issue by afnan** [hellowuxin/vue3-mindmap#32]
I am using mindmap to assign nodes and its children from JS. I find it interesting that it always creates nodes on one side. Can we define the direction of the nodes being created that is left or right?

**Comment by hellowuxin** [comment]
`{ "name":"进阶", "left": true }`

**Comment by afnan** [comment]
> "left": true

Thanks that worked. i had to change `IMindMapStructureField` to prevent linter to throw error

```
export interface IMindMapStructureField {
  name: string;
  left?: boolean;
  children: IMindMapStructureField[]
}

```
