### ISSUE TITLE
作者你好，请问如何让所有树枝在同侧显示和排列，而不是分居根节点左右两侧

### ISSUE THREAD

**Issue by ShenJet** [hellowuxin/vue3-mindmap#36]
作者你好，请问如何让所有树枝在根节点右侧显示和排列，而不是分居根节点左右两侧？

**Comment by hellowuxin** [comment]
默认都是在右侧，除非给节点设了left为true，你看一下readme



Hello,world!



------------------ 原始邮件 ------------------
发件人: ShenJie ***@***.***&gt;
发送时间: 2022年3月4日 17:45
收件人: hellowuxin/vue3-mindmap ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hellowuxin/vue3-mindmap] 作者你好，请问如何让所有树枝在同侧显示和排列，而不是分居根节点左右两侧 (Issue #36)

**Comment by ShenJet** [comment]
作者有无 赞赏途径，请你喝咖啡

**Comment by hellowuxin** [comment]
项目主页右侧（Sponsor this project）有个爱发电，你可以试试
