### ISSUE TITLE
作者您好，我运行之后，button按钮的样式看不到了怎么解决呢？

### ISSUE THREAD

**Issue by NCWUxiaobo** [hellowuxin/vue3-mindmap#38]
鼠标放上去有button形状，但好像透明了。。
<img width="948" alt="4A8A3472-8721-48F0-96C1-B0B025ADCE83" src="https://user-images.githubusercontent.com/63790512/158731807-1693a5c2-586a-4fb3-8ecb-46844e4602f6.png">

**Comment by hellowuxin** [comment]
确保引入样式，确保对应功能开启，如果不行，请尝试自己调试
参考 https://github.com/hellowuxin/vue3-mindmap/issues/34
